/**
 * Copyright 2014 deib-polimi
 * Contact: deib-polimi <santo.lombardo@polimi.it>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 06:55:07 PM CEST 
//


package it.polimi.moda.dmc.cpim.gdm;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
 *       &lt;attribute name="node1" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="node2" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="constrain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="node1MinCard" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="node1MaxCard" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="node2MinCard" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="node2MaxCard" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "edge")
public class Edge {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String name;
    @XmlAttribute(name = "node1", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object node1;
    @XmlAttribute(name = "node2", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object node2;
    @XmlAttribute(name = "constrain")
    protected String constrain;
    @XmlAttribute(name = "node1MinCard", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long node1MinCard;
    @XmlAttribute(name = "node1MaxCard")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger node1MaxCard;
    @XmlAttribute(name = "node2MinCard", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long node2MinCard;
    @XmlAttribute(name = "node2MaxCard")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger node2MaxCard;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the node1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNode1() {
        return node1;
    }

    /**
     * Sets the value of the node1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNode1(Object value) {
        this.node1 = value;
    }

    /**
     * Gets the value of the node2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNode2() {
        return node2;
    }

    /**
     * Sets the value of the node2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNode2(Object value) {
        this.node2 = value;
    }

    /**
     * Gets the value of the constrain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstrain() {
        return constrain;
    }

    /**
     * Sets the value of the constrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstrain(String value) {
        this.constrain = value;
    }

    /**
     * Gets the value of the node1MinCard property.
     * 
     */
    public long getNode1MinCard() {
        return node1MinCard;
    }

    /**
     * Sets the value of the node1MinCard property.
     * 
     */
    public void setNode1MinCard(long value) {
        this.node1MinCard = value;
    }

    /**
     * Gets the value of the node1MaxCard property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNode1MaxCard() {
        return node1MaxCard;
    }

    /**
     * Sets the value of the node1MaxCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNode1MaxCard(BigInteger value) {
        this.node1MaxCard = value;
    }

    /**
     * Gets the value of the node2MinCard property.
     * 
     */
    public long getNode2MinCard() {
        return node2MinCard;
    }

    /**
     * Sets the value of the node2MinCard property.
     * 
     */
    public void setNode2MinCard(long value) {
        this.node2MinCard = value;
    }

    /**
     * Gets the value of the node2MaxCard property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNode2MaxCard() {
        return node2MaxCard;
    }

    /**
     * Sets the value of the node2MaxCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNode2MaxCard(BigInteger value) {
        this.node2MaxCard = value;
    }

}
